import type { Category, MenuItem } from './types'

/**
 * BA Crown Rose menu — June 2026.
 * Hard-coded from the pub's PDF. Prices in GBP.
 *
 * Dietary tags are best-effort: `veg`/`vegan` from the menu text and `ngci`
 * (non-gluten-containing ingredient) from the PDF's NGCI page. The PDF's
 * vegetarian/vegan glyphs did not extract cleanly, so only clear cases are
 * tagged. Full allergen info is available from the pub on request.
 */
export const MENU: MenuItem[] = [
  // ───────────────────────── Starters & Sharing ─────────────────────────
  {
    id: 'chicken-goujons',
    name: 'Crispy Chicken Goujons',
    description: 'Choose tangy BBQ dip or hot Firecracker sauce',
    category: 'Starters & Sharing',
    dietary: [],
    variants: [
      { label: '5pc', price: 6.5 },
      { label: '10pc', price: 12.95 },
      { label: '20pc', price: 19.95 },
    ],
  },
  {
    id: 'halloumi-fries',
    name: 'Halloumi Fries',
    description: 'Topped with mint yoghurt & pomegranate seeds',
    category: 'Starters & Sharing',
    dietary: ['veg'],
    variants: [{ price: 7.75 }],
  },
  {
    id: 'duck-gyozas',
    name: 'Duck Gyozas',
    description: 'Crispy dumplings, tangy soy sauce, spring onions & chillies',
    category: 'Starters & Sharing',
    dietary: [],
    variants: [{ price: 7.25 }],
  },
  {
    id: 'tandoori-skewers',
    name: 'Tandoori Chicken Skewers',
    description: 'Tomato, cucumber & coriander salad, mint raita, crispy onions',
    category: 'Starters & Sharing',
    dietary: ['ngci'],
    variants: [{ price: 8.25 }],
  },
  {
    id: 'salt-pepper-squid',
    name: 'Salt & Pepper Squid',
    description: 'With lime mayonnaise',
    category: 'Starters & Sharing',
    dietary: [],
    variants: [{ price: 9.5 }],
  },
  {
    id: 'prawn-cocktail',
    name: 'Classic Prawn Cocktail',
    description: 'Marie Rose sauce, iceberg lettuce, buttered granary',
    category: 'Starters & Sharing',
    dietary: [],
    variants: [{ price: 9.25 }],
  },
  {
    id: 'potato-skins',
    name: 'Loaded Potato Skins',
    description: 'Bacon & cheese, or red onion & cheese, sour cream dip',
    category: 'Starters & Sharing',
    dietary: [],
    variants: [{ price: 7.95 }],
  },
  {
    id: 'courgette-fritters',
    name: 'Crispy Courgette Fritters',
    description: 'With mint yoghurt dip & pomegranate seeds',
    category: 'Starters & Sharing',
    dietary: ['veg'],
    variants: [{ price: 7.75 }],
  },
  {
    id: 'mini-sausages',
    name: 'Sticky Honey & Mustard Mini Sausages',
    description: 'With mustard mayo',
    category: 'Starters & Sharing',
    dietary: [],
    variants: [
      { label: '5pc', price: 4.75 },
      { label: '10pc', price: 8.95 },
      { label: '20pc', price: 15.5 },
    ],
  },
  {
    id: 'garlic-pizza-bread',
    name: 'Garlic Pizza Bread',
    description: 'Hand-stretched sourdough, plant-based garlic butter',
    category: 'Starters & Sharing',
    dietary: ['veg'],
    variants: [
      { label: '4 slices', price: 7.25 },
      { label: '8 slices', price: 10.5 },
    ],
  },
  {
    id: 'prawn-lollipops',
    name: 'Tiger Prawn Lollipops',
    description: 'Tempura batter, sweet chilli sauce',
    category: 'Starters & Sharing',
    dietary: [],
    variants: [{ price: 9.95 }],
  },
  {
    id: 'loaded-nachos',
    name: 'Loaded Nachos',
    description: 'Cheddar, jalapeños, guacamole, salsa, sour cream (vegan option)',
    category: 'Starters & Sharing',
    dietary: ['veg', 'vegan', 'ngci'],
    variants: [{ price: 9.25 }],
  },
  {
    id: 'soup',
    name: 'Homemade Soup of the Day',
    description: 'Seeded roll & butter',
    category: 'Starters & Sharing',
    dietary: ['veg', 'ngci'],
    variants: [{ price: 7.75 }],
  },
  {
    id: 'cheese-balls',
    name: 'Crispy Melty Cheese Balls',
    description: 'Feta, mozzarella & Cheddar, sweet chilli & sour cream dips',
    category: 'Starters & Sharing',
    dietary: ['veg'],
    variants: [{ price: 8.95 }],
  },
  {
    id: 'corn-ribs',
    name: 'Corn Ribs',
    description: 'Lightly spiced, sweet chilli dip, coriander & lime',
    category: 'Starters & Sharing',
    dietary: ['vegan', 'ngci'],
    variants: [
      { label: '5pc', price: 5.95 },
      { label: '10pc', price: 11.5 },
      { label: '20pc', price: 18.95 },
    ],
  },
  {
    id: 'sharing-platter',
    name: 'Sharing Starter Platter',
    description: 'BBQ ribs, cheesy skins, goujons, garlic ciabatta, onion rings (serves 2-4)',
    category: 'Starters & Sharing',
    dietary: [],
    variants: [{ price: 21.95 }],
  },

  // ───────────────────────────── Mains ─────────────────────────────
  {
    id: 'fish-chips',
    name: 'Fish & Chips',
    description: 'Fresh haddock, skin-on fries, peas, tartare sauce',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 19.5 }],
  },
  {
    id: 'rump-lamb',
    name: 'Rump of Lamb, Salsa Verde',
    description: 'Greek salad with feta, sweet potato fries, pomegranate',
    category: 'Mains',
    dietary: ['ngci'],
    variants: [{ price: 22.5 }],
  },
  {
    id: 'confit-duck',
    name: 'Confit Duck, Peppercorn Sauce',
    description: 'Potato dauphinoise & fresh vegetables',
    category: 'Mains',
    dietary: ['ngci'],
    variants: [{ price: 21.75 }],
  },
  {
    id: 'tex-mex-salad',
    name: 'Deep South Tex Mex Salad',
    description: 'Avocado, sweet potato, Mexican beans, sweetcorn, Cajun lime dressing',
    category: 'Mains',
    dietary: ['vegan', 'ngci'],
    variants: [{ price: 14.95 }],
  },
  {
    id: 'cumberland-sausage',
    name: 'Cumberland Sausage & Mash',
    description: 'Creamy colcannon mash, vegetables & onion gravy',
    category: 'Mains',
    dietary: ['ngci'],
    variants: [{ price: 17.5 }],
  },
  {
    id: 'scampi',
    name: 'Wholetail Breaded Scampi',
    description: 'Skin-on fries, peas & homemade tartare sauce',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 18.5 }],
  },
  {
    id: 'bbq-ribs',
    name: 'Our Famous BBQ Ribs',
    description: 'Baby back pork ribs, BBQ sauce, skin-on fries, coleslaw',
    category: 'Mains',
    dietary: ['ngci'],
    variants: [
      { label: '½ Rack', price: 18.5 },
      { label: 'Full Rack', price: 24.95 },
      { label: 'Mountain', price: 32.95 },
    ],
  },
  {
    id: 'chicken-leek-pie',
    name: 'Chicken, Leek & Ham Pie',
    description: 'Puff pastry top, colcannon mash & fresh vegetables',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 18.95 }],
  },
  {
    id: 'summer-gnocchi',
    name: 'Summer Gnocchi, Roasted Tomato & Spinach',
    description: 'Vegan feta, pea shoots, seeds, basil dressing (veggie feta option)',
    category: 'Mains',
    dietary: ['veg', 'vegan'],
    variants: [{ price: 15.95 }],
  },
  {
    id: 'baked-salmon',
    name: 'Baked Fillet of Salmon',
    description: 'Mustard & caper sauce, roasted new potatoes & green beans',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 20.5 }],
  },
  {
    id: 'chicken-caesar',
    name: 'Chicken Caesar Salad',
    description: 'Croutons, parmesan, anchovies & Caesar dressing',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 17.5 }],
  },
  {
    id: 'ham-egg-chips',
    name: 'Ham, Egg & Chips',
    description: 'Honey-glazed ham, 2 eggs & skin-on fries',
    category: 'Mains',
    dietary: ['ngci'],
    variants: [{ price: 15.95 }],
  },
  {
    id: 'chicken-chorizo-kebabs',
    name: 'Chicken & Chorizo Kebabs',
    description: 'Hot chilli honey glaze, Cajun fries, sour cream & mixed salad',
    category: 'Mains',
    dietary: ['ngci'],
    variants: [{ price: 18.95 }],
  },
  {
    id: 'sirloin-steak',
    name: '8oz Sirloin Steak',
    description: 'Roast tomato, field mushroom, chunky chips',
    category: 'Mains',
    dietary: ['ngci'],
    variants: [{ price: 27.95 }],
  },
  {
    id: 'cajun-ribs-combo',
    name: 'Cajun Chicken & Ribs Combo',
    description: 'Cajun chicken breast, half rack ribs, corn ribs, salad, slaw & fries',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 23.95 }],
  },
  {
    id: 'roast-beef',
    name: 'Roast Sirloin of Beef',
    description: 'Roast potatoes, parsnips, cauli cheese, Yorkshire pudding, gravy',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 23.5 }],
  },
  {
    id: 'roast-turkey',
    name: 'Roast Turkey',
    description: 'Stuffing, pigs in blankets, roast potatoes, cauli cheese, gravy',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 19.95 }],
  },
  {
    id: 'best-of-both-roast',
    name: "'Best of Both' Roast Dinner",
    description: 'Roast sirloin & turkey with pigs in blankets and all the trimmings',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 24.95 }],
  },
  {
    id: 'chestnut-roast',
    name: 'Chestnut Roast',
    description: 'Mushroom, cranberry & pumpkin seeds, trimmings, veggie gravy (vegan option)',
    category: 'Mains',
    dietary: ['veg', 'vegan'],
    variants: [{ price: 19.95 }],
  },
  {
    id: 'fajitas-veg-halloumi',
    name: 'Sizzling Fajitas — Vegetable & Halloumi',
    description: 'Peppers, onions, baby corn, tortillas, cheese, salsa, guac & sour cream',
    category: 'Mains',
    dietary: ['veg'],
    variants: [{ price: 19.95 }],
  },
  {
    id: 'fajitas-steak',
    name: 'Sizzling Fajitas — Steak',
    description: 'Peppers, onions, baby corn, tortillas, cheese, salsa, guac & sour cream',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 21.95 }],
  },
  {
    id: 'fajitas-chicken',
    name: 'Sizzling Fajitas — Chicken',
    description: 'Peppers, onions, baby corn, tortillas, cheese, salsa, guac & sour cream',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 20.75 }],
  },
  {
    id: 'fajitas-steak-chicken',
    name: 'Sizzling Fajitas — Steak & Chicken',
    description: 'Peppers, onions, baby corn, tortillas, cheese, salsa, guac & sour cream',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 24.95 }],
  },
  {
    id: 'lamb-mint-burger',
    name: 'Lamb & Mint Burger',
    description: 'Feta tzatziki, pickled red onions, coleslaw & skin-on fries',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 19.75 }],
  },
  {
    id: 'bacon-double-cheese-burger',
    name: 'Bacon Double Cheese Burger',
    description: 'Double burgers, bacon, Cheddar & cheese sauce, slaw & fries',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 18.95 }],
  },
  {
    id: 'bbq-chicken-burger',
    name: 'BBQ Chicken, Bacon & Cheese Burger',
    description: 'Chargrilled chicken, BBQ sauce, burger sauce, slaw & fries',
    category: 'Mains',
    dietary: [],
    variants: [{ price: 19.5 }],
  },
  {
    id: 'veggie-burger',
    name: 'The Veggie Burger',
    description: 'Cheddar, mushrooms & fried onions, vegan slaw & fries (vegan option)',
    category: 'Mains',
    dietary: ['veg', 'vegan'],
    variants: [{ price: 18.5 }],
  },

  // ─────────────────────────── Lunchtime ───────────────────────────
  {
    id: 'steak-ciabatta',
    name: 'Steak & Crispy Onion Ciabatta',
    description: '5oz steak, mustard mayo, lettuce & tomato, skin-on fries',
    category: 'Lunchtime',
    dietary: [],
    variants: [{ price: 14.5 }],
  },
  {
    id: 'ploughmans-ciabatta',
    name: 'Cheddar Ploughmans Ciabatta',
    description: 'With pickle, skin-on fries',
    category: 'Lunchtime',
    dietary: ['veg'],
    variants: [{ price: 12.5 }],
  },
  {
    id: 'jacket-potato',
    name: 'Jacket Potato',
    description: 'Baked beans & cheese, or beef chilli with sour cream',
    category: 'Lunchtime',
    dietary: [],
    variants: [
      { label: 'Beans & Cheese', price: 10.5 },
      { label: 'Beef Chilli', price: 11.5 },
    ],
  },
  {
    id: 'open-prawn-sandwich',
    name: 'Open Prawn Sandwich',
    description: 'Marie Rose sauce, granary, salad & skin-on fries',
    category: 'Lunchtime',
    dietary: [],
    variants: [{ price: 12.95 }],
  },

  // ───────────────────────────── Sides ─────────────────────────────
  {
    id: 'cheesy-chips',
    name: 'Cheesy Chips',
    description: 'Plain, or spicy Cajun with jalapeños & firecracker sauce',
    category: 'Sides',
    dietary: ['veg'],
    variants: [
      { label: 'Plain', price: 6.25 },
      { label: 'Spicy', price: 7.25 },
    ],
  },
  {
    id: 'chilli-cheesy-chips',
    name: 'Chilli Cheesy Chips',
    description: 'Cheese, spicy beef chilli, jalapeños, firecracker sauce',
    category: 'Sides',
    dietary: [],
    variants: [{ price: 9.95 }],
  },
  {
    id: 'dauphinoise',
    name: 'Potato Dauphinoise',
    category: 'Sides',
    dietary: ['veg'],
    variants: [{ price: 5.25 }],
  },
  {
    id: 'bucket-fries',
    name: 'Bucket of Fries or Chunky Chips',
    description: 'Serves 3-4',
    category: 'Sides',
    dietary: ['vegan'],
    variants: [
      { label: 'Skin-on Fries', price: 13.5 },
      { label: 'Chunky Chips', price: 14.95 },
    ],
  },
  {
    id: 'onion-rings',
    name: 'Onion Rings',
    category: 'Sides',
    dietary: ['vegan'],
    variants: [{ price: 3.95 }],
  },
  {
    id: 'skin-on-fries',
    name: 'Skin-on Fries',
    category: 'Sides',
    dietary: ['vegan'],
    variants: [{ price: 4.5 }],
  },
  {
    id: 'chunky-chips',
    name: 'Chunky Chips',
    category: 'Sides',
    dietary: ['vegan'],
    variants: [{ price: 4.95 }],
  },
  {
    id: 'sweet-potato-fries',
    name: 'Sweet Potato Fries',
    category: 'Sides',
    dietary: ['vegan'],
    variants: [{ price: 5.5 }],
  },
  {
    id: 'coleslaw',
    name: 'Homemade Coleslaw',
    category: 'Sides',
    dietary: ['veg'],
    variants: [{ price: 2.95 }],
  },
  {
    id: 'side-salad-veg',
    name: 'Side Salad or Vegetables',
    category: 'Sides',
    dietary: ['vegan'],
    variants: [{ price: 4.5 }],
  },
  {
    id: 'curry-sauce',
    name: 'Curry Sauce',
    category: 'Sides',
    dietary: ['vegan'],
    variants: [{ price: 2.5 }],
  },
  {
    id: 'pigs-in-blankets',
    name: 'Pigs in Blankets (4)',
    description: 'Bacon-wrapped chipolatas',
    category: 'Sides',
    dietary: [],
    variants: [{ price: 5.5 }],
  },
  {
    id: 'stuffing-balls',
    name: 'Pork, Sage & Onion Stuffing Balls (4)',
    category: 'Sides',
    dietary: [],
    variants: [{ price: 4.95 }],
  },
  {
    id: 'roast-potatoes',
    name: 'Roast Potatoes',
    category: 'Sides',
    dietary: ['vegan'],
    variants: [{ price: 5.25 }],
  },
  {
    id: 'extra-yorkshire',
    name: 'Extra Yorkshire Pudding',
    category: 'Sides',
    dietary: ['veg'],
    variants: [{ price: 2.35 }],
  },

  // ──────────────────────────── Desserts ────────────────────────────
  {
    id: 'apple-crumble',
    name: 'Spiced Apple & Cinnamon Crumble',
    description: "With 'pour your own' hot custard",
    category: 'Desserts',
    dietary: ['veg', 'ngci'],
    variants: [{ price: 7.95 }],
  },
  {
    id: 'sticky-toffee',
    name: 'Homemade Sticky Toffee Pudding',
    description: 'Hot toffee sauce & clotted cream',
    category: 'Desserts',
    dietary: ['veg'],
    variants: [{ price: 8.95 }],
  },
  {
    id: 'chocolate-brownie',
    name: 'Chocolate Brownie',
    description: 'Warm, with chocolate sauce & vanilla ice cream',
    category: 'Desserts',
    dietary: ['veg', 'ngci'],
    variants: [{ price: 8.5 }],
  },
  {
    id: 'biscoff-cheesecake',
    name: 'Biscoff Cheesecake',
    description: 'Biscoff topping & sauce, vegan vanilla ice cream',
    category: 'Desserts',
    dietary: ['vegan'],
    variants: [{ price: 8.95 }],
  },
  {
    id: 'ice-cream',
    name: 'Ice Cream (3 scoops)',
    description: 'Chocolate, vanilla bean, strawberry chunk or butterscotch',
    category: 'Desserts',
    dietary: ['veg'],
    variants: [{ price: 6.95 }],
  },
  {
    id: 'profiteroles',
    name: 'Profiteroles',
    description: 'Two jumbo choux balls, vanilla ice cream, warm chocolate sauce',
    category: 'Desserts',
    dietary: ['veg'],
    variants: [{ price: 9.95 }],
  },
  {
    id: 'party-profiteroles',
    name: 'Party Profiteroles (per piece)',
    description: 'Add as many as you like, warm chocolate sauce',
    category: 'Desserts',
    dietary: ['veg'],
    variants: [{ price: 4.95 }],
  },
  {
    id: 'trio-mini-puddings',
    name: 'Trio of Mini Puddings',
    description: 'Strawberry pavlova, chocolate brownie & mini crumble',
    category: 'Desserts',
    dietary: ['veg'],
    variants: [{ price: 11.5 }],
  },
  {
    id: 'raspberry-sorbet',
    name: 'Raspberry Sorbet',
    description: 'A refreshing, zesty finish',
    category: 'Desserts',
    dietary: ['vegan', 'ngci'],
    variants: [{ price: 7.75 }],
  },
  {
    id: 'cookie-sundae',
    name: 'Chocolate Cookie Sundae',
    description: 'Vanilla & chocolate ice cream, cookie & hot fudge sauce',
    category: 'Desserts',
    dietary: ['veg'],
    variants: [{ price: 8.95 }],
  },
  {
    id: 'eton-mess-sundae',
    name: 'Strawberry Eton Mess Sundae',
    description: 'White chocolate, vanilla ice cream, strawberries & meringue',
    category: 'Desserts',
    dietary: ['veg', 'ngci'],
    variants: [{ price: 8.95 }],
  },
  {
    id: 'home-baked-cookie',
    name: 'Home-Baked Cookie',
    description: 'Chocolate cookie with Belgian chocolate chunks',
    category: 'Desserts',
    dietary: ['veg'],
    variants: [{ price: 2.95 }],
  },
  {
    id: 'mini-pud-drink',
    name: 'Mini Pudding & a Hot Drink',
    description: 'Mini brownie, pavlova or crumble (or after-dinner cocktail option)',
    category: 'Desserts',
    dietary: ['veg'],
    variants: [
      { label: 'With Hot Drink', price: 7.5 },
      { label: 'With Cocktail', price: 12.5 },
    ],
  },

  // ───────────────────────────── Drinks ─────────────────────────────
  {
    id: 'latte',
    name: 'Café Latte / Iced Latte',
    category: 'Drinks',
    dietary: ['veg'],
    variants: [{ price: 4.1 }],
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    category: 'Drinks',
    dietary: ['veg'],
    variants: [{ price: 4.1 }],
  },
  {
    id: 'espresso',
    name: 'Espresso',
    category: 'Drinks',
    dietary: ['vegan'],
    variants: [
      { label: 'Single', price: 3.05 },
      { label: 'Double', price: 3.7 },
    ],
  },
  {
    id: 'americano',
    name: 'Americano / Filter / Decaf',
    category: 'Drinks',
    dietary: ['vegan'],
    variants: [{ price: 3.4 }],
  },
  {
    id: 'hot-chocolate',
    name: 'Hot Chocolate',
    description: 'Choice of milk, soya or oat',
    category: 'Drinks',
    dietary: ['veg'],
    variants: [{ price: 4.45 }],
  },
  {
    id: 'liqueur-coffee',
    name: 'Liqueur Coffee / Baileys Latte',
    category: 'Drinks',
    dietary: [],
    variants: [
      { label: 'Liqueur Coffee', price: 8.25 },
      { label: 'Baileys Latte', price: 7.95 },
    ],
  },
  {
    id: 'pot-of-tea',
    name: 'Pot of English Breakfast / Herbal Tea',
    description: 'Green, peppermint, lemon & ginger or Earl Grey',
    category: 'Drinks',
    dietary: ['vegan'],
    variants: [{ price: 3.95 }],
  },
  {
    id: 'strawberry-shake',
    name: 'Strawberry Shortbread Milkshake',
    description: 'Strawberries & ice cream with crumbly shortbread, whipped cream',
    category: 'Drinks',
    dietary: ['veg'],
    variants: [{ price: 6.25 }],
  },
  {
    id: 'cookies-cream-shake',
    name: "Cookies 'n' Cream Milkshake",
    description: 'Cookie, ice cold milk & choccy ice cream, whipped cream',
    category: 'Drinks',
    dietary: ['veg'],
    variants: [{ price: 6.25 }],
  },
  {
    id: 'vanilla-caramel-shake',
    name: 'Vanilla Caramel Milkshake',
    description: 'Vegan vanilla ice cream, soya milk, vegan cream & caramel',
    category: 'Drinks',
    dietary: ['vegan'],
    variants: [{ price: 6.25 }],
  },
  {
    id: 'passionfruit-mocktini',
    name: 'Passionfruit Mock-tini',
    description: "Gordon's 0%, passionfruit, lime, lemonade shot (alcohol-free)",
    category: 'Drinks',
    dietary: ['vegan'],
    variants: [{ price: 7.25 }],
  },
  {
    id: 'negroni',
    name: 'Negroni',
    description: 'Campari, gin & sweet vermouth',
    category: 'Drinks',
    dietary: [],
    variants: [{ price: 10.5 }],
  },
  {
    id: 'pornstar-martini',
    name: 'Pornstar Martini',
    description: 'Vanilla vodka, passion fruit liqueur, prosecco shot',
    category: 'Drinks',
    dietary: [],
    variants: [{ price: 10.95 }],
  },
  {
    id: 'espresso-martini',
    name: 'Espresso Martini',
    description: 'Vodka, Tia Maria & espresso',
    category: 'Drinks',
    dietary: [],
    variants: [{ price: 10.95 }],
  },
  {
    id: 'mint-choc-moment',
    name: 'Mint Choc Moment',
    description: 'Baileys, Crème de Menthe, crème de cacao & double cream',
    category: 'Drinks',
    dietary: [],
    variants: [{ price: 10.95 }],
  },
  {
    id: 'rusty-nail',
    name: 'Rusty Nail',
    description: 'Scotch whisky, Drambuie & fresh rosemary',
    category: 'Drinks',
    dietary: [],
    variants: [{ price: 8.95 }],
  },
  {
    id: 'godfather',
    name: 'The Godfather',
    description: 'Disaronno, whisky & an orange twist',
    category: 'Drinks',
    dietary: [],
    variants: [{ price: 8.95 }],
  },
  {
    id: 'old-fashioned',
    name: 'Old Fashioned',
    description: 'Bourbon, brown sugar, Angostura bitters, orange twist',
    category: 'Drinks',
    dietary: [],
    variants: [{ price: 8.95 }],
  },
  {
    id: 'big-baileys',
    name: 'The Big Baileys',
    description: '100ml of Baileys over ice',
    category: 'Drinks',
    dietary: [],
    variants: [{ price: 7.05 }],
  },
  {
    id: 'disaronno',
    name: 'Disaronno Amaretto',
    category: 'Drinks',
    dietary: [],
    variants: [
      { label: '25ml', price: 4.5 },
      { label: '50ml', price: 8.15 },
    ],
  },
  {
    id: 'martell-cognac',
    name: 'Martell VS Cognac',
    category: 'Drinks',
    dietary: [],
    variants: [
      { label: '25ml', price: 4.7 },
      { label: '50ml', price: 8.45 },
    ],
  },
  {
    id: 'courvoisier-cognac',
    name: 'Courvoisier VS Cognac',
    category: 'Drinks',
    dietary: [],
    variants: [
      { label: '25ml', price: 5.0 },
      { label: '50ml', price: 8.95 },
    ],
  },
]

/** Display order for category sections. */
export const CATEGORIES: Category[] = [
  'Starters & Sharing',
  'Mains',
  'Lunchtime',
  'Sides',
  'Desserts',
  'Drinks',
]

/** Build a unique selection key for an item + variant index. */
export function skuKey(itemId: string, variantIndex: number): string {
  return `${itemId}::${variantIndex}`
}
